# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeSSD <- function(m, epsilon, max_iter) {
    .Call('markov3d_computeSSD', PACKAGE = 'markov3d', m, epsilon, max_iter)
}

